
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: parking_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # This overrides your application.yml so it connects to the Docker 'db' 
      # instead of 'localhost' (since they are now in Docker together!)
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/parking_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password123
    depends_on:
      - db